### ISSUE TITLE
There is no Gene on index 4 to be replaced.

### ISSUE THREAD

**Issue by troncomputers** [JanPalasek/job-shop-scheduling#1]
Hi!
I'm getting an error `There is no Gene on index 4 to be replaced.`. Is it because my input data is not symmetrical? how to deal with uneven jobs?

INPUT DATA
```
10 6
1  11  5  12
2  10  5  15
1  10  4  15
3  3  4  5  6  1
2  12  5  13  6  11
3  2  6  3
2  8  4  6
2  11  6  12
2  5  3  6  4  4
1  4  3  3  5  2
```

STACKTRACE: 
```
STACKTRACE:
   at GeneticSharp.Domain.Chromosomes.ChromosomeBase.ReplaceGene(Int32 index, Gene gene)
   at JobShopScheduling.GeneticAlgorithm.ScheduleChromosome.FixChromosome() in C:\Users\Adam\Downloads\job-shop-scheduling-master\JobShopScheduling\GeneticAlgorithm\ScheduleChromosome.cs:line 104
   at JobShopScheduling.GeneticAlgorithm.ScheduleFitness.Evaluate(ScheduleChromosome chromosome) in C:\Users\Adam\Downloads\job-shop-scheduling-master\JobShopScheduling\GeneticAlgorithm\ScheduleFitness.cs:line 31
   at JobShopScheduling.GeneticAlgorithm.ScheduleFitness.Evaluate(IChromosome chromosome) in C:\Users\Adam\Downloads\job-shop-scheduling-master\JobShopScheduling\GeneticAlgorithm\ScheduleFitness.cs:line 20
   at GeneticSharp.Domain.GeneticAlgorithm.RunEvaluateFitness(Object chromosome)

```

**Comment by JanPalasek** [comment]
Hello,

there's a hidden assumption in the input files: machines need to be numbered from 0. I modified your input file accordingly and tried it and it seems to work.

Your modified input:
```
10 6
0  11  4  12
1  10  4  15
0  10  3  15
2  3  3  5  5  1
1  12  4  13  5  11
2  2  5  3
1  8  3  6
1  11  5  12
1  5  2  6  3  4
0  4  2  3  4  2
```

Please try it and report back.

I'll add a specification of input files to README.

Append: I'll also try to update .NET Core version and the libraries.

**Comment by troncomputers** [comment]
Yeah, that was it. I've changed couple things in code to match my input data. 

BTW how to get results. It's generating .svg file but I want it like 
```
Machine 0: operations 0, 4, 5, 2
Machine 1: operations 1, 3
```
Does `JobShop jobShop = LoadJobShop(inputPath);` object contain calculated results?

**Comment by JanPalasek** [comment]
Hi, the output, similarly to proposed, will be now written to "{inputFile}.out" file.

The best schedule is now stored in JobShopGeneticAlgorithm.BestSchedule property, too.

I also updated to .Net Core 3.1 and nugget packages.

**Comment by JanPalasek** [comment]
Does everything work as expected?

**Comment by troncomputers** [comment]
Yes ;-) everything is fine and works perfectly. Thanks for help.
